# This is a Postman Environment (YAML v3).
type: environment
name: "Kissariya - Supabase"
values:
  - key: "supabase_url"
    value: "https://ygkeuhatokvkdwwoccty.supabase.co"
    type: default
    enabled: true
  - key: "anon_key"
    value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlna2V1aGF0b2t2a2R3d29jY3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUyNzAyNzksImV4cCI6MjEwMDg0NjI3OX0.E2xOlYdNO_rh7yMN6h3GcygMFQ2d0claAq7jzaH3WUg"
    type: secret
    enabled: true
  - key: "service_role_key"
    value: "cle-service-role-jamais-en-frontend"
    type: secret
    enabled: true
  - key: "admin_email"
    value: "admin@votre-site.com"
    type: default
    enabled: true
  - key: "admin_password"
    value: "mot-de-passe-admin"
    type: secret
    enabled: true
  - key: "search"
    value: "creme"
    type: default
    enabled: true
  - key: "category_slug"
    value: "soins-visage"
    type: default
    enabled: true
  - key: "slug"
    value: "creme-hydratante"
    type: default
    enabled: true
  - key: "file_name"
    value: "test-upload.jpg"
    type: default
    enabled: true
  - key: "access_token"
    value: ""
    type: secret
    enabled: true
  - key: "refresh_token"
    value: ""
    type: secret
    enabled: true
  - key: "user_id"
    value: ""
    type: default
    enabled: true
  - key: "product_id"
    value: ""
    type: default
    enabled: true
  - key: "order_id"
    value: ""
    type: default
    enabled: true
  - key: "category_id"
    value: ""
    type: default
    enabled: true
  - key: "promo_id"
    value: ""
    type: default
    enabled: true
  - key: "settings_id"
    value: ""
    type: default
    enabled: true